import {
  Activity,
  Airplay,
  AlarmClock,
  Anchor,
  Aperture,
  Apple,
  Archive,
  Atom,
  AtSign,
  AudioLines,
  Award,
  BadgeCheck,
  Banana,
  Banknote,
  BarChart3,
  Beer,
  Bell,
  Bike,
  Binary,
  Bird,
  Bitcoin,
  Blocks,
  Book,
  Bookmark,
  BookmarkCheck,
  BookMarked,
  BookOpen,
  BookText,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Candy,
  Car,
  Carrot,
  Cat,
  ChartLine,
  ChartPie,
  ChefHat,
  Cherry,
  Chrome,
  CircleDollarSign,
  CircleHelp,
  CircuitBoard,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSun,
  Cloudy,
  Code,
  Codepen,
  Codesandbox,
  Coffee,
  Coins,
  Compass,
  Component,
  Contact,
  Container,
  Contrast,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Croissant,
  Crop,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dice5,
  Dices,
  Disc3,
  Dog,
  Download,
  Dribbble,
  Droplet,
  Drumstick,
  Dumbbell,
  Egg,
  Eraser,
  Eye,
  EyeOff,
  Factory,
  Feather,
  Figma,
  File,
  FileCode,
  FileJson,
  Files,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderGit,
  FolderOpen,
  Footprints,
  Frame,
  Framer,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  Github,
  Gitlab,
  GitMerge,
  GitPullRequest,
  Glasses,
  Globe,
  Globe2,
  GraduationCap,
  Grape,
  Grid3x3,
  Guitar,
  Hammer,
  HandCoins,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Highlighter,
  History,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  Image,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Instagram,
  Key,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Laugh,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Link2,
  Linkedin,
  ListChecks,
  ListMusic,
  ListTodo,
  Lock,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  Microscope,
  Milestone,
  Monitor,
  MonitorPlay,
  Moon,
  Mountain,
  Mouse,
  MousePointer2,
  MousePointerClick,
  Music,
  Music2,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Paintbrush,
  Palette,
  Paperclip,
  Pen,
  Pencil,
  PencilRuler,
  PenLine,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  Play,
  Plug,
  Pocket,
  Podcast,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radio,
  RadioTower,
  Rainbow,
  Receipt,
  Recycle,
  Rocket,
  Router,
  Rss,
  Ruler,
  Sailboat,
  Salad,
  Satellite,
  Save,
  Scale,
  ScanLine,
  ScanSearch,
  School,
  Scissors,
  Search,
  SearchCheck,
  Send,
  Server,
  Settings,
  Shapes,
  Share2,
  Shell,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Signature,
  Sliders,
  Smartphone,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Speaker,
  Spline,
  Sprout,
  Squirrel,
  Stamp,
  Star,
  StickyNote,
  Store,
  Sun,
  Sunrise,
  Sunset,
  SwatchBook,
  Sword,
  Swords,
  Table,
  Tablet,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  TextSearch,
  Thermometer,
  ThumbsUp,
  Ticket,
  Timer,
  TrainFront,
  TreePine,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Twitch,
  Twitter,
  Type,
  Umbrella,
  Unplug,
  User,
  UserCheck,
  UserPlus,
  Users,
  UtensilsCrossed,
  Video,
  Voicemail,
  Volleyball,
  Volume2,
  Wallet,
  Wand2,
  Warehouse,
  Watch,
  Webhook,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Youtube,
  Zap,
  ZoomIn,
  type LucideIcon,
} from 'lucide-react';

/** Curated category icon palette, grouped by theme; only verified lucide exports. */

export type CategoryIconOption = {
  name: string;
  label: string;
  Icon: LucideIcon;
  group: string;
};

type Entry = [string, string, LucideIcon];

const GROUPS: Array<{ id: string; label: string; entries: Entry[] }> = [
  {
    id: 'common',
    label: '通用',
    entries: [
      ['Folder', '通用目录', Folder],
      ['Bookmark', '书签', Bookmark],
      ['Star', '收藏', Star],
      ['Heart', '喜欢', Heart],
      ['Home', '主页', Home],
      ['Inbox', '收件箱', Inbox],
      ['Archive', '归档', Archive],
      ['Tag', '标签', Tag],
      ['Flag', '旗帜', Flag],
      ['Pin', '固定', Pin],
      ['Gift', '礼物', Gift],
      ['Trophy', '奖杯', Trophy],
      ['Award', '奖章', Award],
      ['Medal', '勋章', Medal],
      ['Crown', '皇冠', Crown],
      ['Gem', '宝石', Gem],
      ['Diamond', '钻石', Diamond],
      ['Flame', '热门', Flame],
      ['Rocket', '起飞 / 工具', Rocket],
      ['Search', '搜索 / 检索', Search],
      ['SearchCheck', '精确搜索', SearchCheck],
      ['ZoomIn', '放大', ZoomIn],
      ['Eye', '浏览', Eye],
      ['EyeOff', '隐身', EyeOff],
      ['FolderOpen', '打开目录', FolderOpen],
      ['Files', '多文件', Files],
      ['File', '文件', File],
      ['Copy', '副本', Copy],
      ['Link', '链接', Link],
      ['Link2', '外链', Link2],
      ['Share2', '分享', Share2],
      ['BadgeCheck', '认证', BadgeCheck],
      ['BookmarkCheck', '已收藏', BookmarkCheck],
      ['Stamp', '印章', Stamp],
      ['Hourglass', '沙漏', Hourglass],
      ['History', '历史', History],
      ['Info', '信息', Info],
      ['CircleHelp', '帮助', CircleHelp],
      ['TriangleAlert', '注意', TriangleAlert],
    ],
  },
  {
    id: 'dev',
    label: '开发 · 技术',
    entries: [
      ['Code', '代码', Code],
      ['Terminal', '终端', Terminal],
      ['Bug', '调试', Bug],
      ['Cpu', '硬件 / 芯片', Cpu],
      ['Database', '数据库', Database],
      ['Server', '服务器', Server],
      ['HardDrive', '硬盘', HardDrive],
      ['Cloud', '云服务', Cloud],
      ['Wifi', '网络', Wifi],
      ['Globe', '互联网', Globe],
      ['Globe2', '全球', Globe2],
      ['FolderGit', 'Git 仓库', FolderGit],
      ['Github', 'GitHub', Github],
      ['Gitlab', 'GitLab', Gitlab],
      ['Codepen', 'Codepen', Codepen],
      ['Codesandbox', 'CodeSandbox', Codesandbox],
      ['Chrome', '浏览器', Chrome],
      ['Keyboard', '键盘', Keyboard],
      ['Laptop', '笔记本', Laptop],
      ['Smartphone', '手机', Smartphone],
      ['Tablet', '平板', Tablet],
      ['Plug', '插件', Plug],
      ['Boxes', '容器 / 模块', Boxes],
      ['Box', '盒子', Box],
      ['Package', '软件包', Package],
      ['Puzzle', '插件 / 拼图', Puzzle],
      ['Wrench', '工具', Wrench],
      ['Hammer', '建造', Hammer],
      ['Sliders', '调参', Sliders],
      ['Settings', '设置', Settings],
      ['Fingerprint', '指纹 / 身份', Fingerprint],
      ['Key', '密钥', Key],
      ['Lock', '安全锁', Lock],
      ['Shield', '安全', Shield],
      ['GitBranch', 'Git 分支', GitBranch],
      ['GitCommitHorizontal', 'Git 提交', GitCommitHorizontal],
      ['GitPullRequest', '合并请求', GitPullRequest],
      ['GitMerge', 'Git 合并', GitMerge],
      ['Workflow', '工作流', Workflow],
      ['Network', '网络拓扑', Network],
      ['Braces', '代码片段', Braces],
      ['FileCode', '代码文件', FileCode],
      ['FileJson', 'JSON', FileJson],
      ['Binary', '二进制', Binary],
      ['Monitor', '显示器', Monitor],
      ['Mouse', '鼠标', Mouse],
      ['MousePointerClick', '点击', MousePointerClick],
      ['Router', '路由器', Router],
      ['QrCode', '二维码', QrCode],
      ['ScanLine', '扫描', ScanLine],
      ['Radar', '雷达', Radar],
      ['Container', '容器', Container],
      ['Unplug', '断开连接', Unplug],
      ['TestTube', '测试', TestTube],
      ['Component', '组件', Component],
      ['Blocks', '区块', Blocks],
      ['Webhook', 'Webhook', Webhook],
      ['CircuitBoard', '电路', CircuitBoard],
      ['RadioTower', '信号塔', RadioTower],
      ['Satellite', '卫星', Satellite],
      ['FileSearch', '代码搜索', FileSearch],
    ],
  },
  {
    id: 'ai',
    label: 'AI · 数据',
    entries: [
      ['Bot', 'AI / 机器人', Bot],
      ['Brain', '大脑 / 智能', Brain],
      ['Sparkles', '灵光', Sparkles],
      ['Wand2', '魔法棒', Wand2],
      ['Zap', '效率', Zap],
      ['FlaskConical', '实验', FlaskConical],
      ['Microscope', '科研', Microscope],
      ['Atom', '原子 / 物理', Atom],
      ['Telescope', '望远镜', Telescope],
      ['BarChart3', '柱状图', BarChart3],
      ['ChartLine', '折线图', ChartLine],
      ['ChartPie', '饼图', ChartPie],
      ['PieChart', '占比', PieChart],
      ['TrendingUp', '趋势', TrendingUp],
      ['Activity', '活动 / 监控', Activity],
      ['Target', '目标', Target],
      ['BrainCircuit', '神经网络', BrainCircuit],
      ['ScanSearch', '智能搜索', ScanSearch],
      ['TextSearch', '语义搜索', TextSearch],
      ['Gauge', '仪表盘', Gauge],
      ['Scale', '权衡 / 法律', Scale],
      ['Dices', '随机', Dices],
    ],
  },
  {
    id: 'design',
    label: '设计 · 创意',
    entries: [
      ['Palette', '调色板', Palette],
      ['Paintbrush', '画笔', Paintbrush],
      ['Brush', '毛笔', Brush],
      ['Pen', '钢笔', Pen],
      ['Pencil', '铅笔', Pencil],
      ['Aperture', '光圈', Aperture],
      ['Camera', '相机', Camera],
      ['Image', '图片', Image],
      ['Figma', 'Figma', Figma],
      ['Framer', 'Framer', Framer],
      ['Dribbble', 'Dribbble', Dribbble],
      ['Layers', '图层', Layers],
      ['LayoutGrid', '布局', LayoutGrid],
      ['Grid3x3', '九宫格', Grid3x3],
      ['Scissors', '裁剪', Scissors],
      ['Paperclip', '附件', Paperclip],
      ['Feather', '羽毛 / 轻盈', Feather],
      ['Droplet', '水滴', Droplet],
      ['Rainbow', '彩虹', Rainbow],
      ['Lightbulb', '灵感', Lightbulb],
      ['Type', '字体', Type],
      ['Shapes', '形状', Shapes],
      ['Frame', '画框', Frame],
      ['Ruler', '标尺', Ruler],
      ['PenTool', '矢量笔', PenTool],
      ['PencilRuler', '设计工具', PencilRuler],
      ['Spline', '曲线', Spline],
      ['SwatchBook', '色卡', SwatchBook],
      ['Eraser', '橡皮擦', Eraser],
      ['Contrast', '对比度', Contrast],
      ['Crop', '裁切', Crop],
      ['Highlighter', '荧光笔', Highlighter],
      ['Signature', '签名', Signature],
    ],
  },
  {
    id: 'learn',
    label: '学习 · 阅读',
    entries: [
      ['Book', '书', Book],
      ['BookOpen', '阅读', BookOpen],
      ['Library', '图书馆', Library],
      ['Notebook', '笔记本', Notebook],
      ['GraduationCap', '学习', GraduationCap],
      ['FileText', '文档', FileText],
      ['Quote', '引用', Quote],
      ['Clipboard', '剪贴板', Clipboard],
      ['Newspaper', '资讯', Newspaper],
      ['Rss', 'RSS 订阅', Rss],
      ['Mail', '邮件', Mail],
      ['Calculator', '计算器', Calculator],
      ['Calendar', '日历', Calendar],
      ['Clock', '时间', Clock],
      ['AlarmClock', '闹钟', AlarmClock],
      ['Timer', '计时器', Timer],
      ['Languages', '翻译 / 语言', Languages],
      ['BookMarked', '标记书', BookMarked],
      ['BookText', '教材', BookText],
      ['PenLine', '笔记', PenLine],
      ['NotebookPen', '手记', NotebookPen],
      ['StickyNote', '便签', StickyNote],
      ['Presentation', '演示', Presentation],
      ['Table', '表格', Table],
      ['FileSpreadsheet', '电子表格', FileSpreadsheet],
      ['ListChecks', '清单', ListChecks],
      ['ListTodo', '待办', ListTodo],
      ['Milestone', '里程碑', Milestone],
      ['CalendarCheck', '日程', CalendarCheck],
      ['CalendarDays', '排期', CalendarDays],
      ['Printer', '打印', Printer],
      ['ClipboardList', '待办清单', ClipboardList],
      ['ClipboardCheck', '核对', ClipboardCheck],
    ],
  },
  {
    id: 'media',
    label: '影音 · 娱乐',
    entries: [
      ['Music', '音乐', Music],
      ['Music2', '音符', Music2],
      ['ListMusic', '歌单', ListMusic],
      ['Headphones', '耳机', Headphones],
      ['Mic', '麦克风', Mic],
      ['Podcast', '播客', Podcast],
      ['Radio', '电台', Radio],
      ['Speaker', '音箱', Speaker],
      ['Film', '影视', Film],
      ['Video', '视频', Video],
      ['Youtube', 'YouTube', Youtube],
      ['Twitch', 'Twitch', Twitch],
      ['Twitter', 'Twitter / X', Twitter],
      ['Instagram', 'Instagram', Instagram],
      ['Linkedin', 'LinkedIn', Linkedin],
      ['Gamepad2', '游戏', Gamepad2],
      ['Dice5', '桌游 / 骰子', Dice5],
      ['Ghost', 'Ghost', Ghost],
      ['Sword', '剑', Sword],
      ['Tent', '露营', Tent],
      ['Clapperboard', '电影', Clapperboard],
      ['Tv', '电视', Tv],
      ['MonitorPlay', '观影', MonitorPlay],
      ['Disc3', '唱片', Disc3],
      ['AudioLines', '声波', AudioLines],
      ['Volume2', '音量', Volume2],
      ['Play', '播放', Play],
      ['Guitar', '吉他', Guitar],
      ['Piano', '钢琴', Piano],
    ],
  },
  {
    id: 'life',
    label: '生活 · 出行',
    entries: [
      ['Coffee', '咖啡', Coffee],
      ['Beer', '啤酒', Beer],
      ['Wine', '红酒', Wine],
      ['CupSoda', '饮料', CupSoda],
      ['Pizza', '美食', Pizza],
      ['Cake', '甜点', Cake],
      ['Drumstick', '鸡腿', Drumstick],
      ['Egg', '蛋', Egg],
      ['Grape', '水果', Grape],
      ['ShoppingBag', '购物', ShoppingBag],
      ['ShoppingCart', '购物车', ShoppingCart],
      ['CreditCard', '信用卡', CreditCard],
      ['Wallet', '钱包', Wallet],
      ['Banknote', '现金', Banknote],
      ['Coins', '硬币', Coins],
      ['Bitcoin', '比特币', Bitcoin],
      ['Landmark', '银行 / 政府', Landmark],
      ['Plane', '飞机', Plane],
      ['Airplay', '投屏', Airplay],
      ['Car', '汽车', Car],
      ['Bike', '自行车', Bike],
      ['Ship', '船', Ship],
      ['Anchor', '锚', Anchor],
      ['Truck', '卡车', Truck],
      ['Map', '地图', MapIcon],
      ['MapPin', '定位', MapPin],
      ['Compass', '指南针', Compass],
      ['Footprints', '足迹', Footprints],
      ['Mountain', '登山', Mountain],
      ['Umbrella', '雨伞', Umbrella],
      ['Store', '商店', Store],
      ['Percent', '折扣', Percent],
      ['Tags', '标签组', Tags],
      ['Receipt', '账单', Receipt],
      ['PiggyBank', '存钱罐', PiggyBank],
      ['CircleDollarSign', '外币', CircleDollarSign],
      ['HandCoins', '付款', HandCoins],
      ['Cookie', '饼干', Cookie],
      ['Croissant', '可颂', Croissant],
      ['Candy', '糖果', Candy],
      ['Popcorn', '爆米花', Popcorn],
      ['UtensilsCrossed', '餐饮', UtensilsCrossed],
      ['ChefHat', '厨师', ChefHat],
      ['Soup', '汤羹', Soup],
      ['Banana', '香蕉', Banana],
      ['Cherry', '樱桃', Cherry],
      ['Carrot', '胡萝卜', Carrot],
      ['Salad', '沙拉', Salad],
      ['Bus', '公交', Bus],
      ['TrainFront', '火车', TrainFront],
      ['Sailboat', '帆船', Sailboat],
      ['Hotel', '酒店', Hotel],
      ['Warehouse', '仓库', Warehouse],
      ['Factory', '工厂', Factory],
      ['School', '学校', School],
      ['Hospital', '医院', Hospital],
    ],
  },
  {
    id: 'nature',
    label: '自然 · 健康',
    entries: [
      ['Sun', '太阳', Sun],
      ['Sunrise', '日出', Sunrise],
      ['Sunset', '日落', Sunset],
      ['Moon', '月亮', Moon],
      ['Snowflake', '雪', Snowflake],
      ['CloudRain', '下雨', CloudRain],
      ['Leaf', '叶子', Leaf],
      ['Flower2', '花', Flower2],
      ['TreePine', '松树', TreePine],
      ['Recycle', '环保', Recycle],
      ['Cat', '猫', Cat],
      ['Dog', '狗', Dog],
      ['Rabbit', '兔子', Rabbit],
      ['Fish', '鱼', Fish],
      ['HeartPulse', '心率', HeartPulse],
      ['Pill', '药品', Pill],
      ['Dumbbell', '健身', Dumbbell],
      ['LifeBuoy', '救生圈', LifeBuoy],
      ['Sprout', '幼苗', Sprout],
      ['Bird', '鸟', Bird],
      ['Squirrel', '松鼠', Squirrel],
      ['Turtle', '乌龟', Turtle],
      ['Shell', '贝壳', Shell],
      ['Wind', '风', Wind],
      ['CloudSun', '多云', CloudSun],
      ['CloudLightning', '雷雨', CloudLightning],
      ['Cloudy', '阴天', Cloudy],
      ['Thermometer', '温度', Thermometer],
      ['Apple', '苹果', Apple],
    ],
  },
  {
    id: 'work',
    label: '工作 · 社交',
    entries: [
      ['Briefcase', '工作', Briefcase],
      ['Building2', '公司', Building2],
      ['MessagesSquare', '讨论', MessagesSquare],
      ['MessageCircle', '聊天', MessageCircle],
      ['Phone', '电话', Phone],
      ['Bell', '通知', Bell],
      ['ThumbsUp', '点赞', ThumbsUp],
      ['Smile', '表情', Smile],
      ['Laugh', '开心', Laugh],
      ['Glasses', '眼镜', Glasses],
      ['Watch', '手表', Watch],
      ['Shirt', '服饰', Shirt],
      ['Ticket', '票务', Ticket],
      ['Save', '保存', Save],
      ['Download', '下载', Download],
      ['Filter', '筛选', Filter],
      ['Magnet', '磁铁', Magnet],
      ['Infinity', '无限', InfinityIcon],
      ['Hexagon', '六边形', Hexagon],
      ['MousePointer2', '指针', MousePointer2],
      ['Pocket', '口袋', Pocket],
      ['Users', '群组', Users],
      ['User', '用户', User],
      ['UserPlus', '添加成员', UserPlus],
      ['UserCheck', '成员核验', UserCheck],
      ['Contact', '联系人', Contact],
      ['Send', '发送', Send],
      ['AtSign', '艾特', AtSign],
      ['Megaphone', '公告', Megaphone],
      ['PhoneCall', '来电', PhoneCall],
      ['Voicemail', '语音信箱', Voicemail],
      ['Swords', '竞技', Swords],
      ['Volleyball', '排球', Volleyball],
    ],
  },
];

const RAW_ENTRIES: Entry[] = GROUPS.flatMap((g) => g.entries);

const GROUP_OF = new Map<string, string>();
for (const group of GROUPS) {
  for (const [name] of group.entries) {
    if (!GROUP_OF.has(name)) GROUP_OF.set(name, group.id);
  }
}

export const CATEGORY_ICON_GROUPS = GROUPS.map((g) => ({
  id: g.id,
  label: g.label,
}));

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = RAW_ENTRIES.map(
  ([name, label, Icon]) => ({
    name,
    label,
    Icon,
    group: GROUP_OF.get(name) ?? 'common',
  }),
);

const ICON_MAP = new Map(CATEGORY_ICON_OPTIONS.map((o) => [o.name, o]));

/** Resolves a stored icon name to its component; `null` renders the fallback. */
export function resolveCategoryIcon(name: string | null | undefined):
  | { Icon: LucideIcon; option: CategoryIconOption | null }
  | null {
  if (!name) return null;
  const option = ICON_MAP.get(name);
  if (option) return { Icon: option.Icon, option };
  return { Icon: Folder, option: null };
}
