import {
  Activity,
  Airplay,
  AlarmClock,
  Anchor,
  Aperture,
  Archive,
  Atom,
  Award,
  Banknote,
  BarChart3,
  Beer,
  Bell,
  Bike,
  Bitcoin,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartLine,
  ChartPie,
  Chrome,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Codepen,
  Codesandbox,
  Coffee,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dice5,
  Dog,
  Download,
  Dribbble,
  Droplet,
  Drumstick,
  Dumbbell,
  Egg,
  Feather,
  Figma,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderGit,
  Footprints,
  Framer,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Github,
  Gitlab,
  Glasses,
  Globe,
  Globe2,
  GraduationCap,
  Grape,
  Grid3x3,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Home,
  Image,
  Inbox,
  Infinity as InfinityIcon,
  Instagram,
  Key,
  Keyboard,
  Landmark,
  Laptop,
  Laugh,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Linkedin,
  ListMusic,
  Lock,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  MessageCircle,
  MessagesSquare,
  Mic,
  Microscope,
  Moon,
  Mountain,
  MousePointer2,
  Music,
  Music2,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  Paperclip,
  Pen,
  Pencil,
  Phone,
  PieChart,
  Pill,
  Pin,
  Pizza,
  Plane,
  Plug,
  Pocket,
  Podcast,
  Puzzle,
  Quote,
  Rabbit,
  Radio,
  Rainbow,
  Recycle,
  Rocket,
  Rss,
  Save,
  Scissors,
  Server,
  Settings,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Tablet,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Twitch,
  Twitter,
  Umbrella,
  Video,
  Wallet,
  Wand2,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Curated category icon palette, grouped by theme; only verified lucide exports. */

export type CategoryIconOption = {
  name: string;
  label: string;
  Icon: LucideIcon;
  group: string;
};

type Entry = [string, string, LucideIcon];

const GROUPS: Array<{ id: string; label: string; entries: Entry[] }> = [
  {
    id: 'common',
    label: '通用',
    entries: [
      ['Folder', '通用目录', Folder],
      ['Bookmark', '书签', Bookmark],
      ['Star', '收藏', Star],
      ['Heart', '喜欢', Heart],
      ['Home', '主页', Home],
      ['Inbox', '收件箱', Inbox],
      ['Archive', '归档', Archive],
      ['Tag', '标签', Tag],
      ['Flag', '旗帜', Flag],
      ['Pin', '固定', Pin],
      ['Gift', '礼物', Gift],
      ['Trophy', '奖杯', Trophy],
      ['Award', '奖章', Award],
      ['Medal', '勋章', Medal],
      ['Crown', '皇冠', Crown],
      ['Gem', '宝石', Gem],
      ['Diamond', '钻石', Diamond],
      ['Flame', '热门', Flame],
      ['Rocket', '起飞 / 工具', Rocket],
    ],
  },
  {
    id: 'dev',
    label: '开发 · 技术',
    entries: [
      ['Code', '代码', Code],
      ['Terminal', '终端', Terminal],
      ['Bug', '调试', Bug],
      ['Cpu', '硬件 / 芯片', Cpu],
      ['Database', '数据库', Database],
      ['Server', '服务器', Server],
      ['HardDrive', '硬盘', HardDrive],
      ['Cloud', '云服务', Cloud],
      ['Wifi', '网络', Wifi],
      ['Globe', '互联网', Globe],
      ['Globe2', '全球', Globe2],
      ['FolderGit', 'Git 仓库', FolderGit],
      ['Github', 'GitHub', Github],
      ['Gitlab', 'GitLab', Gitlab],
      ['Codepen', 'Codepen', Codepen],
      ['Codesandbox', 'CodeSandbox', Codesandbox],
      ['Chrome', '浏览器', Chrome],
      ['Keyboard', '键盘', Keyboard],
      ['Laptop', '笔记本', Laptop],
      ['Smartphone', '手机', Smartphone],
      ['Tablet', '平板', Tablet],
      ['Plug', '插件', Plug],
      ['Boxes', '容器 / 模块', Boxes],
      ['Box', '盒子', Box],
      ['Package', '软件包', Package],
      ['Puzzle', '插件 / 拼图', Puzzle],
      ['Wrench', '工具', Wrench],
      ['Hammer', '建造', Hammer],
      ['Sliders', '调参', Sliders],
      ['Settings', '设置', Settings],
      ['Fingerprint', '指纹 / 身份', Fingerprint],
      ['Key', '密钥', Key],
      ['Lock', '安全锁', Lock],
      ['Shield', '安全', Shield],
    ],
  },
  {
    id: 'ai',
    label: 'AI · 数据',
    entries: [
      ['Bot', 'AI / 机器人', Bot],
      ['Brain', '大脑 / 智能', Brain],
      ['Sparkles', '灵光', Sparkles],
      ['Wand2', '魔法棒', Wand2],
      ['Zap', '效率', Zap],
      ['FlaskConical', '实验', FlaskConical],
      ['Microscope', '科研', Microscope],
      ['Atom', '原子 / 物理', Atom],
      ['Telescope', '望远镜', Telescope],
      ['BarChart3', '柱状图', BarChart3],
      ['ChartLine', '折线图', ChartLine],
      ['ChartPie', '饼图', ChartPie],
      ['PieChart', '占比', PieChart],
      ['TrendingUp', '趋势', TrendingUp],
      ['Activity', '活动 / 监控', Activity],
      ['Target', '目标', Target],
    ],
  },
  {
    id: 'design',
    label: '设计 · 创意',
    entries: [
      ['Palette', '调色板', Palette],
      ['Paintbrush', '画笔', Paintbrush],
      ['Brush', '毛笔', Brush],
      ['Pen', '钢笔', Pen],
      ['Pencil', '铅笔', Pencil],
      ['Aperture', '光圈', Aperture],
      ['Camera', '相机', Camera],
      ['Image', '图片', Image],
      ['Figma', 'Figma', Figma],
      ['Framer', 'Framer', Framer],
      ['Dribbble', 'Dribbble', Dribbble],
      ['Layers', '图层', Layers],
      ['LayoutGrid', '布局', LayoutGrid],
      ['Grid3x3', '九宫格', Grid3x3],
      ['Scissors', '裁剪', Scissors],
      ['Paperclip', '附件', Paperclip],
      ['Feather', '羽毛 / 轻盈', Feather],
      ['Droplet', '水滴', Droplet],
      ['Rainbow', '彩虹', Rainbow],
      ['Lightbulb', '灵感', Lightbulb],
    ],
  },
  {
    id: 'learn',
    label: '学习 · 阅读',
    entries: [
      ['Book', '书', Book],
      ['BookOpen', '阅读', BookOpen],
      ['Library', '图书馆', Library],
      ['Notebook', '笔记本', Notebook],
      ['GraduationCap', '学习', GraduationCap],
      ['FileText', '文档', FileText],
      ['Quote', '引用', Quote],
      ['Clipboard', '剪贴板', Clipboard],
      ['Newspaper', '资讯', Newspaper],
      ['Rss', 'RSS 订阅', Rss],
      ['Mail', '邮件', Mail],
      ['Calculator', '计算器', Calculator],
      ['Calendar', '日历', Calendar],
      ['Clock', '时间', Clock],
      ['AlarmClock', '闹钟', AlarmClock],
      ['Timer', '计时器', Timer],
    ],
  },
  {
    id: 'media',
    label: '影音 · 娱乐',
    entries: [
      ['Music', '音乐', Music],
      ['Music2', '音符', Music2],
      ['ListMusic', '歌单', ListMusic],
      ['Headphones', '耳机', Headphones],
      ['Mic', '麦克风', Mic],
      ['Podcast', '播客', Podcast],
      ['Radio', '电台', Radio],
      ['Speaker', '音箱', Speaker],
      ['Film', '影视', Film],
      ['Video', '视频', Video],
      ['Youtube', 'YouTube', Youtube],
      ['Twitch', 'Twitch', Twitch],
      ['Twitter', 'Twitter / X', Twitter],
      ['Instagram', 'Instagram', Instagram],
      ['Linkedin', 'LinkedIn', Linkedin],
      ['Gamepad2', '游戏', Gamepad2],
      ['Dice5', '桌游 / 骰子', Dice5],
      ['Ghost', 'Ghost', Ghost],
      ['Sword', '剑', Sword],
      ['Tent', '露营', Tent],
    ],
  },
  {
    id: 'life',
    label: '生活 · 出行',
    entries: [
      ['Coffee', '咖啡', Coffee],
      ['Beer', '啤酒', Beer],
      ['Wine', '红酒', Wine],
      ['CupSoda', '饮料', CupSoda],
      ['Pizza', '美食', Pizza],
      ['Cake', '甜点', Cake],
      ['Drumstick', '鸡腿', Drumstick],
      ['Egg', '蛋', Egg],
      ['Grape', '水果', Grape],
      ['ShoppingBag', '购物', ShoppingBag],
      ['ShoppingCart', '购物车', ShoppingCart],
      ['CreditCard', '信用卡', CreditCard],
      ['Wallet', '钱包', Wallet],
      ['Banknote', '现金', Banknote],
      ['Coins', '硬币', Coins],
      ['Bitcoin', '比特币', Bitcoin],
      ['Landmark', '银行 / 政府', Landmark],
      ['Plane', '飞机', Plane],
      ['Airplay', '投屏', Airplay],
      ['Car', '汽车', Car],
      ['Bike', '自行车', Bike],
      ['Ship', '船', Ship],
      ['Anchor', '锚', Anchor],
      ['Truck', '卡车', Truck],
      ['Map', '地图', MapIcon],
      ['MapPin', '定位', MapPin],
      ['Compass', '指南针', Compass],
      ['Footprints', '足迹', Footprints],
      ['Mountain', '登山', Mountain],
      ['Umbrella', '雨伞', Umbrella],
    ],
  },
  {
    id: 'nature',
    label: '自然 · 健康',
    entries: [
      ['Sun', '太阳', Sun],
      ['Sunrise', '日出', Sunrise],
      ['Sunset', '日落', Sunset],
      ['Moon', '月亮', Moon],
      ['Snowflake', '雪', Snowflake],
      ['CloudRain', '下雨', CloudRain],
      ['Leaf', '叶子', Leaf],
      ['Flower2', '花', Flower2],
      ['TreePine', '松树', TreePine],
      ['Recycle', '环保', Recycle],
      ['Cat', '猫', Cat],
      ['Dog', '狗', Dog],
      ['Rabbit', '兔子', Rabbit],
      ['Fish', '鱼', Fish],
      ['HeartPulse', '心率', HeartPulse],
      ['Pill', '药品', Pill],
      ['Dumbbell', '健身', Dumbbell],
      ['LifeBuoy', '救生圈', LifeBuoy],
    ],
  },
  {
    id: 'work',
    label: '工作 · 社交',
    entries: [
      ['Briefcase', '工作', Briefcase],
      ['Building2', '公司', Building2],
      ['MessagesSquare', '讨论', MessagesSquare],
      ['MessageCircle', '聊天', MessageCircle],
      ['Phone', '电话', Phone],
      ['Bell', '通知', Bell],
      ['ThumbsUp', '点赞', ThumbsUp],
      ['Smile', '表情', Smile],
      ['Laugh', '开心', Laugh],
      ['Glasses', '眼镜', Glasses],
      ['Watch', '手表', Watch],
      ['Shirt', '服饰', Shirt],
      ['Ticket', '票务', Ticket],
      ['Save', '保存', Save],
      ['Download', '下载', Download],
      ['Filter', '筛选', Filter],
      ['Magnet', '磁铁', Magnet],
      ['Infinity', '无限', InfinityIcon],
      ['Hexagon', '六边形', Hexagon],
      ['MousePointer2', '指针', MousePointer2],
      ['Pocket', '口袋', Pocket],
    ],
  },
];

const RAW_ENTRIES: Entry[] = GROUPS.flatMap((g) => g.entries);

const GROUP_OF = new Map<string, string>();
for (const group of GROUPS) {
  for (const [name] of group.entries) {
    if (!GROUP_OF.has(name)) GROUP_OF.set(name, group.id);
  }
}

export const CATEGORY_ICON_GROUPS = GROUPS.map((g) => ({
  id: g.id,
  label: g.label,
}));

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = RAW_ENTRIES.map(
  ([name, label, Icon]) => ({
    name,
    label,
    Icon,
    group: GROUP_OF.get(name) ?? 'common',
  }),
);

const ICON_MAP = new Map(CATEGORY_ICON_OPTIONS.map((o) => [o.name, o]));

/** Resolves a stored icon name to its component; `null` renders the fallback. */
export function resolveCategoryIcon(name: string | null | undefined):
  | { Icon: LucideIcon; option: CategoryIconOption | null }
  | null {
  if (!name) return null;
  const option = ICON_MAP.get(name);
  if (option) return { Icon: option.Icon, option };
  return { Icon: Folder, option: null };
}

/** Colour tokens with static Tailwind classes. */
export const CATEGORY_COLOR_OPTIONS = [
  'violet',
  'teal',
  'orange',
  'blue',
  'purple',
  'rose',
  'red',
  'amber',
  'green',
  'cyan',
] as const;

export type CategoryColorToken = (typeof CATEGORY_COLOR_OPTIONS)[number];

const COLOR_SWATCH_CLASSES: Record<CategoryColorToken, string> = {
  violet: 'bg-violet-500',
  teal: 'bg-teal-500',
  orange: 'bg-orange-500',
  blue: 'bg-blue-500',
  purple: 'bg-purple-500',
  rose: 'bg-rose-500',
  red: 'bg-red-500',
  amber: 'bg-amber-500',
  green: 'bg-green-500',
  cyan: 'bg-cyan-500',
};

export function colorSwatchClass(token: string | null | undefined): string {
  if (!token) return 'bg-muted-foreground/30';
  return COLOR_SWATCH_CLASSES[token as CategoryColorToken] ?? 'bg-muted-foreground/30';
}
